# Use a imagem oficial do Python para Streamlit
FROM python:3.9-slim

# Configuração do diretório de trabalho no container
WORKDIR /app

# Copiar arquivos necessários
COPY ./requirements.txt .
COPY ./app/main_app.py .

# Instalar dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta 8501 para o Streamlit
EXPOSE 8501

# Comando para iniciar o Streamlit
CMD ["streamlit", "run", "--server.port", "8501", "main_app.py"]
